// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw9z0KSJ8Ytg_asotqbwDzwo9GB1yBOnk',
    appId: '1:691187061356:web:2464f61eb69fbbd95e3e49',
    messagingSenderId: '691187061356',
    projectId: 'chat-test-f2697',
    authDomain: 'chat-test-f2697.firebaseapp.com',
    storageBucket: 'chat-test-f2697.firebasestorage.app',
    measurementId: 'G-45TC9YXHE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfmXv4ZJNFfCANxVOyG4lJJm7801wZnIQ',
    appId: '1:691187061356:android:6d327985cd3c97495e3e49',
    messagingSenderId: '691187061356',
    projectId: 'chat-test-f2697',
    storageBucket: 'chat-test-f2697.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJAN9DbSuMqAtNtA7kHsEPEbfcGobZLYE',
    appId: '1:691187061356:ios:1eeb11adcdfc8ab45e3e49',
    messagingSenderId: '691187061356',
    projectId: 'chat-test-f2697',
    storageBucket: 'chat-test-f2697.firebasestorage.app',
    iosBundleId: 'com.example.chatTest',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJAN9DbSuMqAtNtA7kHsEPEbfcGobZLYE',
    appId: '1:691187061356:ios:1eeb11adcdfc8ab45e3e49',
    messagingSenderId: '691187061356',
    projectId: 'chat-test-f2697',
    storageBucket: 'chat-test-f2697.firebasestorage.app',
    iosBundleId: 'com.example.chatTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw9z0KSJ8Ytg_asotqbwDzwo9GB1yBOnk',
    appId: '1:691187061356:web:1f471c731da0c11f5e3e49',
    messagingSenderId: '691187061356',
    projectId: 'chat-test-f2697',
    authDomain: 'chat-test-f2697.firebaseapp.com',
    storageBucket: 'chat-test-f2697.firebasestorage.app',
    measurementId: 'G-9KT76KCRCY',
  );
}
